# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_obtained', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date obtained')),
            ],
            options={
                'verbose_name': 'Badges Model',
            },
        ),
        migrations.CreateModel(
            name='SpecificBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.Badges')),
                ('badge_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_owner', to=settings.AUTH_USER_MODEL, verbose_name='badge_owner')),
            ],
        ),
        migrations.AddField(
            model_name='badges',
            name='badge_owner',
            field=models.ManyToManyField(through='badges.SpecificBadge', to=settings.AUTH_USER_MODEL),
        ),
    ]
