# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgesExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtained', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date obtained')),
            ],
        ),
        migrations.RemoveField(
            model_name='specificbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='specificbadge',
            name='badge_owner',
        ),
        migrations.RemoveField(
            model_name='badges',
            name='badge_owner',
        ),
        migrations.RemoveField(
            model_name='badges',
            name='date_obtained',
        ),
        migrations.RemoveField(
            model_name='badges',
            name='description',
        ),
        migrations.DeleteModel(
            name='SpecificBadge',
        ),
        migrations.AddField(
            model_name='badgesextended',
            name='badge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badgesextended', to='badges.Badges'),
        ),
        migrations.AddField(
            model_name='badgesextended',
            name='badge_owners',
            field=models.ManyToManyField(blank=True, related_name='badge_owner', to=settings.AUTH_USER_MODEL, verbose_name='badge_owner'),
        ),
    ]
