# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('name', models.CharField(max_length=140, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='view count')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model3d', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Models3d',
                'ordering': ['-date_added'],
                'verbose_name': 'Model3d',
                'get_latest_by': 'date_added',
            },
        ),
    ]
